# copy right
# Licenses http://www.apache.org/licenses/LICENSE-2.0
# more info see https://docs.docker.com/compose/compose-file/ or https://docker.github.io/compose/compose-file/
version: '3.7'

networks:
  default:
#volumes:
#  web-data:
services:
  go-micro-restful-demo-consul:
    command: -server -bootstrap -rejoin
    image: progrium/consul:latest
    hostname: "registry"
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
  go-micro-restful-demo:
    container_name: "${ROOT_NAME}"
    image: alpine:3.10
    links:
      - go-micro-restful-demo-consul
    ports:
      - "31000:31000"
    volumes:
      - "./build/test/${DIST_VERSION}/:/usr/src/myapp"
#      - "./log:/usr/src/myapp/log"
    environment:
      - ENV_WEB_HTTPS_ENABLE=false
    working_dir: "/usr/src/myapp"
    command: ./main --registry_address=registry:8500 --register_interval=5 --register_ttl=10 api
